Add delay option
tier4/rosbag2 pull request #3
Opened 2021-06-21 00:11 UTC by kosuke55

`--delay`を追加しました．
`ros2 bag play <rosbag2 file> -d 10`
とすると10秒間のスリープ後にbagが再生します．

2021-06-21 00:57 UTC, hayato-m126 requested changes
追加したdelayオプションで，引数の数が合わないって感じのエラーが出ています。

❯ ros2 bag play input_bag
Traceback (most recent call last):
  File "/opt/ros/foxy/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.9.9', 'console_scripts', 'ros2')()
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2cli/cli.py", line 67, in main
    rc = extension.main(parser=parser, args=args)
  File "/home/hyt/ros_ws/autoware.proj.eva/build/ros2bag/ros2bag/command/bag.py", line 38, in main
    return extension.main(args=args)
  File "/home/hyt/ros_ws/autoware.proj.eva/build/ros2bag/ros2bag/verb/play.py", line 102, in main
    rosbag2_transport_py.play(
TypeError: function takes at most 11 keyword arguments (12 given)

2021-06-21 01:15 UTC, kosuke55 commented
なんでしょう.. こちらで再現ができないです．ここで12個渡せるようになっているのですが．
https://github.com/tier4/rosbag2/pull/3/files#diff-1b70d0d9ad3b3d220e816e98de8302f3904b6d3a44728166fd3b2c989c34a982R288-R300
`ros2 bag play -h`で--delayオプション表示されますか？

2021-06-21 01:28 UTC, hayato-m126 commented
delayオプション表示されていますね。

https://user-images.githubusercontent.com/16977736/122695482-6effcb80-d27b-11eb-81bf-ed5e10113143.mp4

2021-06-21 01:36 UTC, kosuke55 commented
動画ありがとうございます．表示されていますね．
`rm -rf build/rosbag2* install/rosbag2*` で再ビルドで治らないでしょうか？

2021-06-21 01:59 UTC, kosuke55 commented
ワークスペースからつくり直しましたが，やはり使えてエラー再現できなかったです．
```
mkdir -p tmp_ws/src
cd tmp_ws/src
clone git@github.com:tier4/rosbag2.git -b feature/delay
cd ..
source /opt/ros/foxy/setup.bash 
colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --symlink-install --packages-up-to rosbag2
ros2 bag play -h  # delayない
source install/setup.bash
ros2 bag play -h  # delayある
ros2 bag play /media/kosuke55/sandisk_ssd/rosbag/ros2/ryuyo-sample/
```

2021-06-21 02:18 UTC, hayato-m126 approved these changes
ワークスペースをrosbag2用に切り出して確認したら動きました。
なんかゴミがいてうまく動いていなかった模様です。すみません。

2021-06-21 02:19 UTC, merged

2021-06-21 07:01 UTC, vios-fish commented
@mitsudome-r logsimでこのオプションを使うことになりそうで､  galacticにもこのオプションはないと聞きました｡
移行の目的の一つにT4フォークをなくしたいがあると思っているので､ この修正をGalacticへ持っていけるように､ サポートお願いしてもいいでしょうか?

2021-06-21 07:06 UTC, kenji-miyake commented
@vios-fish @hayato-m126 rosbag2ではなく、launch側での対応は難しいんですか？普通にTimerActionとかでできそうな気もしています。

2021-06-21 08:11 UTC, hayato-m126 commented
私の知識不足でTimerAction知らなかったので，ROS1と同じようにdelayを入れたらいいじゃないかという発想でした。
個人的にはROS1にもあるオプションなのでROS2の公式の方にdelayオプション取り込んでもらう方がいいかなと思っています。

公式の方に取り込まれなさそうとかなら，改めてrosbag2のオプションじゃなくlaunchで頑張るという方向にしたいです。

2021-06-21 08:24 UTC, kenji-miyake commented
ROS1にオプションがあるのは、ROS1ではlaunchのdelayがなかったので、という理由かもです？
ROS Answersか、rosbag2のIssueで聞いてみるのが良いのではないでしょうか。

2021-06-22 01:44 UTC, hayato-m126 commented
issueで聞きました。
https://github.com/ros2/rosbag2/issues/786